import argparse
import numpy as np

parser = argparse.ArgumentParser()
parser.add_argument('--image_path', type=str, default='./PaviaU.mat')
parser.add_argument('--GT_path', type=str, default='./PaviaU_gt.mat')
parser.add_argument('--PCA_dim', type=int, default=3)
parser.add_argument('--feature_extraction_method', default='mixed')
parser.add_argument('--GLCM_window_size', type=int, default=19)
parser.add_argument('--GLCM_step', type=list,default=[1])
parser.add_argument('--GLCM_angles', type=list, default=[0, np.pi/4, np.pi/2, 3*np.pi/4])
parser.add_argument('--GLCM_gray_dim', type=int, default=5)
parser.add_argument('--LBP_window_size', type=int, default=19)
parser.add_argument('--LBP_R', type=int, default=1)
parser.add_argument('--LBP_N', type=int, default=4)
parser.add_argument('--LBP_gray_dim', type=int, default=8)
parser.add_argument('--Gabor_frequency', type=float, default=0.6)
parser.add_argument('--Gabor_scale', type=int, default=5)
parser.add_argument('--Gabor_angle', type=int, default=8)
parser.add_argument('--Gabor_gray_dim', type=int, default=8)
parser.add_argument('--train_data_ratio', type=float, default=0.01)
parser.add_argument('--classify_method', default='KNN')
parser.add_argument('--neighbor_num', type=int, default=3)
parser = parser.parse_args()
